### PR TITLE
[fix] resolve size of font in header

### LINKED ISSUE #23: [Bug]: Navigation text is smaller than body text
### Describe the issue

The navigation text is smaller than the main body text, and is quite striking in its difference IMO:

image

With the body text already set to `font: 300 1.25rem/1.75rem "Nunito", sans-serif;` I think it should be adjusted at least `1.0rem;` in the following CSS:

`/static/css/main.css`, line 356
```css
nav .pill {
  padding: 0 0.5rem;
  **font-size: 1.0rem;**
  text-align: center;
}
```

`/static/css/main.css`, line 855
```css
nav ul li {
  **font-size: 1.0rem;**
}
```

Renders the nav the following way:
image

### Link to page

https://cc3-preview.netlify.app/

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jerdog**
This PR fixes #23 by adjusting the `font-size:` to `1rem;` for the `.nav` element where it previously was `0.75rem` which made it significantly smaller than the body text.

### CODE REVIEW

**Comment by CoralineAda** [comment]
I think we need to adjust the media query breakpoint. The "Resources" link wraps somewhere between 800 and 900 width.
Screenshot 2024-09-19 at 5 35 43 PM

**Comment by jerdog** [comment]
Yeah that's a good call. I'll take a look

**Comment by jerdog** [comment]
It breaks at 870px due to the margins set on lists:

```css
ul,
ol {
  list-style-position: inside;
  margin: 1.5rem 0 1.5rem 1.5rem;
}
```

If we move the breakpoint to `min-width: 980px`, then we preserve that margins on the sides of the navbar/header

image

According to [CSS-Tricks](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/), specifically for [Laptops](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/#aa-laptops), we would have a pretty good display at 980px, and the browser window isn't taking up a lot of screen real estate at that point

image

**Comment by CoralineAda** [comment]
Sounds good, I'll keep an eye out for a new push and we'll get it merged!

**Review by CoralineAda — APPROVED** [review]
Brilliant, thanks Jeremy

**Pull request merged**
